export enum WorkoutType {
  KRAFTTRAINING = 0,
  CARDIO = 1,
  PLYOMETRICS = 2,
  SPIEL_SIMULATION = 3,
  TECHNISCHE_DRILLS = 4,
  WETTKAMPF = 5,
  AUFWAERMEN = 6,
  MOBILITY = 7,
  DEHNEN = 8,
  REGENERATION = 9,
  PREHAB = 10
}